name: "Trigger external automation event on card"
description: "Trigger external automation event on an AgilePlace card"
inputs:
  host:
    description: AgilePlace Url (https://mycompany.leankit.com)
    required: true
  apiToken:
    description: Api token with write access to your AgilePlace board
    required: true
  cardId:
    description: Card Id
    required: true
  eventName:
    description: Name of the event to trigger
    required: true
outputs:
  error:
    description: Status message for errors
runs:
  using: "node20"
  main: "dist/index.js"
