name: "Block or unblock a card"
description: "Block or unblock a card"
inputs:
  host:
    description: AgilePlace Url (https://mycompany.leankit.com)
    required: true
  apiToken:
    description: Api token with read access to your AgilePlace board
    required: true
  cardId:
    description: Id of the card
    required: true
  isBlocked:
    description: Whether to block or unblock the card
    required: true
  blockReason:
    description: Block reason
    required: false
    default: Blocked by automation
outputs:
  error:
    description: Status message for errors
runs:
  using: "node20"
  main: "dist/index.js"
