name: "Validate Card Custom Fields"
description: "Validate the custom fields on a card"
inputs:
  host:
    description: AgilePlace Url (https://mycompany.leankit.com)
    required: true
  apiToken:
    description: Api token with read access to your AgilePlace board
    required: true
  cardId:
    description: Id of the card
    required: true
  requiredCustomFields:
    description: The labels or ids of the custom fields to validate
    required: true
  customFields:
    description: Custom fields values, if available already
outputs:
  error:
    description: Status message for errors
  customFieldsByLabel:
    description: Custom field values indexed by label
  customFieldsById:
    description: Custom field values indexed by field id
runs:
  using: "node20"
  main: "dist/index.js"
