name: "Create Card"
description: "Create a LeanKit card"
inputs:
  host:
    description: LeanKit Url (https://mycompany.leankit.com)
    required: true
  apiToken:
    description: Api token with write access to your LeanKit board
    required: true
  boardId:
    description: Board Id for the new card
    required: true
  title:
    description: Title of the new card
    required: true
  laneId:
    description: Optionally specify lane id for the new card. Default drop lane will be used when not set.
    required: false
  typeId:
    description: Optionally specify a card type id to use. Default card type will be used when not set.
    required: false
outputs:
  message:
    description: Status message for errors or ignored pull requests
  createdCardId:
    description: id of created card (when successful)
runs:
  using: "node16"
  main: "dist/index.js"
