name: "Create Card"
description: "Create an AgilePlace card"
inputs:
  host:
    description: AgilePlace Url (https://mycompany.leankit.com)
    required: true
  apiToken:
    description: Api token with write access to your AgilePlace board
    required: true
  boardId:
    description: Board Id for the new card
    required: true
  title:
    description: Title of the new card
    required: true
  laneId:
    description: Optionally specify lane id for the new card. Default drop lane will be used when not set.
    required: false
  typeId:
    description: Optionally specify a card type id to use. Default card type will be used when not set.
    required: false
  customId:
    description: Optionally specify header for the new card.
    required: false
  externalLink:
    description: Optionally specify a link.
    required: false
  linkLabel:
    description: Optionally specify a label for the link.
    required: false
outputs:
  error:
    description: Status message for errors
  createdCardId:
    description: id of created card (when successful)
runs:
  using: "node20"
  main: "dist/index.js"
